--[[
    Imperial Export for FiveM
DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOUR DOING! Ripping or repurposing this script is not allowed.
]]--

fx_version 'cerulean'
game 'gta5'

author 'Zippy OFC'
description 'Imperial CAD FiveM integration'
version '1.2.5'

ui_page 'plugins/ImperialTablet/html/index.html'

shared_script {  
    'config.lua',
    'Library/colors.lua',    -- Colors library (This list may require more colors!)
    'Library/vehicles.lua',   -- vehicles library (Update addon vehicles as needed)
    '@ox_lib/init.lua',
}

server_script {
    'utils/imperialEmergency.lua',
    'utils/imperialCharacter.lua',
    'main/sv.lua',
    'utils/framework.lua',
    'utils/misc.lua',
    'plugins/**/sv_*.lua',
    'main/sv_calls.lua',
    --'plugins/**/sv_*.js',
}

client_script {
    'main/cl.lua',
    --'plugins/**/cl_*.js',
    'plugins/**/cl_*.lua',
    'utils/cl_fw.lua'
}

dependencies {
    'ox_lib'
}

files {
    'plugins/**/html/*.html',
    'plugins/**/html/*.js',
    'plugins/**/html/*.png'
}
