--[[
    Imperial Export for FiveM
DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOUR DOING! Ripping or repurposing this script is not allowed.
]]--

fx_version 'cerulean'
game 'gta5'

author 'Zippy OFC'
description 'Imperial CAD FiveM integration'
version '1.0.5'

ui_page 'plugins/ImperialTablet/html/index.html'

server_script {
    'utils/imperialEmergency.lua',
    'utils/imperialCharacter.lua',
    'main/sv.lua',
    'utils/framework.lua',
    'plugins/CivilianInt/server.lua',
}

client_script {
    'main/cl.lua',
    'plugins/ImperialTablet/main.lua',
    'plugins/CivilianInt/client.lua',
    'Library/colors.lua',    -- Colors library (This list may require more colors!)
    'Library/vehicles.lua'   -- vehicles library (Update addon vehicles as needed)
}

shared_script {  'config.lua'
}

dependencies {
    'ImperialLocation',
    'ox_lib'
}

files {
    'plugins/ImperialTablet/html/index.html',
    'plugins/ImperialTablet/html/script.js',
}