--[[
    Imperial Export for FiveM
DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOUR DOING!
]]--

local function getVersionFromManifest()
    local path = GetResourcePath(GetCurrentResourceName()) .. '/fxmanifest.lua'
    local file = io.open(path, "r")
    if file then
        local content = file:read("*a")
        file:close()

        for line in string.gmatch(content, "[^\r\n]+") do
            local value = string.match(line, "^version%s+'(.+)'$")
            if value then
                return value
            end
        end
    end
    return 'unknown'
end

local versionUrl = 'https://raw.githubusercontent.com/Zippy01/ImperialCAD/main/version.json'
local latestVersion = "0.0.0.0"

local function decodeJsonResponse(raw, context)
    if not raw or raw == "" then
        if Config.debug then print("[ImperialCAD] Empty response while decoding " .. context .. ".") end
        return nil
    end

    local ok, decoded = pcall(json.decode, raw)
    if not ok or type(decoded) ~= "table" then
        print("[ImperialCAD] Invalid JSON response while decoding " .. context .. ".")
        return nil
    end

    return decoded
end

local function checkForUpdates()
    local currentVersion = getVersionFromManifest()
    local debugMode = Config.debug and "^2Enabled^7" or "^1Disabled^7"

    local function checkConvarStatus(name)
        local value = GetConvar(name, "")
        if not value or value == "" then
            return "^1Missing^7"
        elseif #value < 15 then
            return "^3Present (Possibly Invalid)^7"
        else
            return "^2Present (Appears Valid)^7"
        end
    end

    local commIdStatus = checkConvarStatus("imperial_community_id")
    local apiKeyStatus = checkConvarStatus("imperialAPI")

    PerformHttpRequest(versionUrl, function(err, responseText, headers)
        local status = "Unknown"
        local updateAvailable = false
        local latest = "Unknown"

        if err == 200 and responseText and responseText:match("{") then
            local success, data = pcall(json.decode, responseText)
            if success and data and data.latestVersion then
                latestVersion = data.latestVersion
                latest = latestVersion

                if latestVersion ~= currentVersion then
                    status = "^1Update Available^7"
                    updateAvailable = true
                else
                    status = "^2Up to Date^7"
                end
            else
                status = "^3Version Check Failed^7"
            end
        else
            status = "^1Failed to Reach Update Server^7"
        end

        print("\n^4=======================[ ImperialCAD ]=======================^7")
        print("  ^5Current Version:^7   " .. currentVersion)
        print("  ^5Latest Version:^7    " .. latest)
        print("  ^5Update Status:^7     " .. status)
        print("  ^5Debug Mode:^7        " .. debugMode)
        print("  ^5Community ID:^7      " .. commIdStatus)
        print("  ^5API Key:^7           " .. apiKeyStatus)
        print("^4============================================================\n^7")

        if updateAvailable then
            print("^3[ImperialCAD]^7 Visit ^4https://github.com/Zippy01/ImperialCAD^7 to download the latest version.")
        end
    end, 'GET', '')
end

AddEventHandler('onResourceStart', function(resourceName)
    if resourceName ~= GetCurrentResourceName() then return end

    if GetCurrentResourceName() ~= "ImperialCAD" then
        print("[^1ImperialCAD^7] Invalid script name. This script MUST be named ^3'ImperialCAD'^7 to work properly!")
        return
    end

    print('[ImperialCAD] Hello World!')

    if Config.DisableVersionCheck then return end

    Wait(5000)
    checkForUpdates()
end)

if Config.cadkickonleave then
AddEventHandler('playerDropped', function(reason, resourceName, clientDropReason)
    local playerName = GetPlayerName(source)
     print('Player' .. playerName .. ' dropped, telling ImperialCAD to cleanup')
    
     local discordId = getDiscordId(source)
     if not discordId then
        print("^3[WARN]^7 Discord ID not found for " .. playerName .. "Cannot attempt cleanup")
     else
        if Config.debug then
        print("Attempting to mark "..playerName.." off duty in cad, using the discord id "..discordId)
        end

     exports["ImperialCAD"]:Booter({
        users_discordID = discordId
     }, function(success, resultData)
        if success then
            if Config.debug then
            print("[ImperialCleanup] Player was successfully marked off duty, and cleaned up in the CAD")
            end
        else
            if Config.debug then
            print("[ImperialCleanup] Unable to mark user off duty, This player might not be logged in")
            end
        end
     end)
    end end)
end

RegisterNetEvent('ImperialCAD:New911')
AddEventHandler('ImperialCAD:New911', function(callData)

    if type(callData) ~= "table" or not callData.name or not callData.street or not callData.crossStreet or not callData.postal or not callData.info then
        print("[Imperial911] Missing required call data to create a new 911 call, Will not create.")
        return  
    end
    local player = source
    local coords = callData.coords

    exports["ImperialCAD"]:Create911Call({
        name = callData.name,
        street = callData.street,
        crossStreet = callData.crossStreet,
        info = callData.info,
        postal = callData.postal,
        city = callData.city,
        county = callData.county
    }, function(success, resultData)
        if success then
            local apires = decodeJsonResponse(resultData, "911 call create")
            if not apires or not apires.response or not apires.response.callId then
                print("^1[API_ERROR]^7 Invalid response or call ID not found")
                return false
            end

            local callNum = apires.response.callnum
            print("[Imperial911] 911 Call was successfully created")
             
            TriggerEvent('Imperial:911ChatMessage', callData.name, callData.street, callData.info, callData.crossStreet, callData.postal, callNum)
        
            if Config.callBlip then
            TriggerEvent("ImperialCAD:911Blip", coords)
            end

            TriggerClientEvent('ImperialCAD:Client:Notify', player, "Your call was successfully sent to emergency services.")

            else

                TriggerClientEvent('ImperialCAD:Client:Notify', player, "Looks like dispatch is having trouble, We let officers know tho.")
                TriggerEvent('Imperial:911ChatMessage', callData.name, callData.street, callData.info, callData.crossStreet, callData.postal)
                    if Config.callBlip then
                        TriggerEvent("ImperialCAD:911Blip", coords)
                    end
            end
    end)
end)

function Notify(message, playerId)
    if playerId and message then
        if Config.debug then print("[ImperialCAD] Sending notification to player " .. playerId) end
        TriggerClientEvent('chat:addMessage', playerId, {
         color = {255, 0, 0},
         multiline = true,
         args = {"ImperialCAD", message}
        })
    elseif not message then
        print("[IMPERIAL_SV_NOTIFY] No message provided")
    elseif not playerId then
        print("[IMPERIAL_SV_NOTIFY] No playerId provided")
    else
        print("[IMPERIAL_SV_NOTIFY] Couldnt send message")
    end
end

if Config.PlateThroughChat then
RegisterNetEvent('ImperialCAD:CheckPlate')
AddEventHandler('ImperialCAD:CheckPlate', function(callData)
    local src = source
    local plate = callData and callData.plate

    if Config.debug then
        print("[ImperialCAD] Plate lookup requested: " .. tostring(plate))
    end

    if not plate or plate == "" then
        print("[ImperialCAD] Plate lookup skipped: missing plate.")
        return
    end

    exports["ImperialCAD"]:CheckPlate({
        plate = plate
    }, function(success, resultData)
        if not success or not resultData then
            if Config.debug then
                print("[ImperialCAD] Plate lookup failed for " .. plate .. ".")
            end
            Notify("Plate lookup failed for " .. plate .. ". Is it registered?", src)
            return
        end

        local decoded, data = pcall(json.decode, resultData)
        if not decoded or type(data) ~= "table" then
            print("[ImperialCAD] Plate lookup returned invalid JSON for " .. plate .. ".")
            Notify("Plate lookup returned an invalid CAD response for " .. plate .. ".", src)
            return
        end

        local response = data.response
        if type(response) ~= "table" then
            print("[ImperialCAD] Plate lookup returned no vehicle data for " .. plate .. ".")
            Notify("Plate lookup found no vehicle data for " .. plate .. ".", src)
            return
        end

        local messages = {}
        local missingFields = {}

        local function getPlateField(label, ...)
            local names = {...}

            for _, name in ipairs(names) do
                if response[name] ~= nil then
                    return response[name]
                end
            end

            for key, value in pairs(response) do
                local lowerKey = string.lower(tostring(key))
                for _, name in ipairs(names) do
                    if lowerKey == string.lower(name) then
                        return value
                    end
                end
            end

            table.insert(missingFields, label)
            return nil
        end

        local owner = getPlateField("owner", "owner", "Owner")
        local resultPlate = getPlateField("plate", "plate", "Plate") or plate
        local stolen = getPlateField("stolen", "stolen", "Stolen")
        local insurance = getPlateField("insurance", "insurance", "Insurance")
        local insuranceStatus = getPlateField("insurance_status", "insurance_status", "insuranceStatus", "InsuranceStatus")
        local business = getPlateField("business", "business", "Business")
        local expStatus = getPlateField("expStatus", "expStatus", "exp_status", "ExpStatus")
        local ownerWanted = getPlateField("owner_wanted", "owner_wanted", "ownerWanted", "OwnerWanted")
        local ownerDlStatus = getPlateField("owner_dl_status", "owner_dl_status", "ownerDlStatus", "OwnerDLStatus")
        local vin = getPlateField("vin", "vin", "VIN", "Vin")

        if Config.debug then
            print("[ImperialCAD] Plate lookup succeeded: " .. resultPlate)
            if owner then print("[ImperialCAD] Plate owner: " .. tostring(owner)) end
            if vin then print("[ImperialCAD] Plate VIN: " .. tostring(vin)) end
            if #missingFields > 0 then
                print("[ImperialCAD] Plate response missing fields: " .. table.concat(missingFields, ", "))
            end
        end

        if stolen == true then
            table.insert(messages, "Stolen Vehicle")
        end

        if insurance ~= true then
            table.insert(messages, "No Insurance")
        end

        if insurance == true and insuranceStatus and insuranceStatus ~= "ACTIVE" then
            table.insert(messages, "Invalid Insurance")
        end

        if business == true then
            table.insert(messages, "Commercial Vehicle")
        end

        if expStatus == false then
            table.insert(messages, "Invalid Vehicle registration")
        end

        if ownerWanted == true then
            table.insert(messages, "Owner Wanted")
        end

        if ownerDlStatus and ownerDlStatus ~= "ACTIVE" then
            table.insert(messages, "Invalid license")
        end

        local detailMessage = "Plate " .. resultPlate
        if owner then
            detailMessage = detailMessage .. " | Owner: " .. tostring(owner)
        end
        if vin then
            detailMessage = detailMessage .. " | VIN: " .. tostring(vin)
        end
        Notify(detailMessage, src)

        if #messages > 0 then
            Notify("The following flags/alerts were found for plate: " .. resultPlate, src)
            TriggerClientEvent('ImperialCAD:Client:Notify', src, json.encode(messages))
        else
            Notify("No flags or alerts found for plate: " .. resultPlate, src)
        end
    
    end)
end)
end

RegisterNetEvent('ImperialCAD:TrafficStop')
AddEventHandler('ImperialCAD:TrafficStop', function(callData)
    local player = source
    if type(callData) ~= "table" then
        Notify("[TS] Unable to create traffic stop", player)
        return
    end

    exports["ImperialCAD"]:CreateCall({
        users_discordID = getDiscordId(source),
        street = callData.street,
        cross_street = callData.crossStreet,
        postal = callData.postal,
        city = callData.city,
        county = callData.county,
        info = callData.info,
        nature = Config.trafficsnature,
        status = Config.trafficsstatus,
        priority = Config.trafficspriority
    }, function(success, resultData)
        if success then
            local apires = decodeJsonResponse(resultData, "traffic stop create")
            if not apires or not apires.response or not apires.response.callId then
                if Config.debug then print("^1[ERROR]^7 Invalid response or call ID not found") end
                Notify("[TS] Unable to create traffic stop", player)
                return
            end
            local callnum = apires.response.callnum
            if Config.debug then print("Traffic Stop created successfully: Call ID -", callnum) end
            Notify("[TS] Traffic stop created succesfully, Call Number: "..callnum, player)
        else
            Notify("[TS] Unable to create traffic stop", player)
            print(resultData)
        end
    end)
end)

RegisterNetEvent('ImperialCAD:AttachCall')
AddEventHandler('ImperialCAD:AttachCall', function(callData)
local player = source
    if type(callData) ~= "table" or not callData.callnum then
        Notify("[Attach] Missing call number", player)
        return
    end

    exports["ImperialCAD"]:AttachCall({
        users_discordID = getDiscordId(source),
        callnum = callData.callnum
    }, function(success, resultData)
        local result = decodeJsonResponse(resultData, "attach call")
        if not result then
            Notify("[Attach] Unable to attach you, invalid CAD response", player)
            return
        end
        local status = result.status
        local message = result.message
        local response = result.response

        if success and status ~= "success" then success = false end

        if status == "NOT_RUN" then
            status = "Unkown error and status"
        elseif status == "BUSY" then
            status = "You must be on duty and available to accept new calls"
        elseif status == "NoSelfDisp" then
            status = "Disptach has marked emergency calls as dispatch only, Please check your cad or reference dispatch"
        end
        
        if not success then
            Notify(string.format("[Attach] Unable to attach you, reason: %s", status), player)
        elseif success and response and response.callnum then
            Notify("[Attach] Attached to call number "..response.callnum, player)
        elseif success then
            Notify("[Attach] Attached to call, but CAD did not return a call number", player)
        elseif not success and Config.debug then
            Notify(string.format("[Attach - Debug] Unable to attach you, Status: %s | Reason: %s", status, message), player)
        end
    end)
end)

RegisterNetEvent('ImperialCAD:CloseCall')
AddEventHandler('ImperialCAD:CloseCall', function(callData)
    if type(callData) ~= "table" or not callData.callId then return end

    exports["ImperialCAD"]:DeleteCall({
        discordId = getDiscordId(source),
        callId = callData.callId,
    }, function(success, resultData)
    end)
end)

RegisterNetEvent('ImperialCAD:Panic')
AddEventHandler('ImperialCAD:Panic', function(callData)
    if type(callData) ~= "table" then return end

    exports["ImperialCAD"]:Panic({
        users_discordID = getDiscordId(source),
        postal = callData.postal,
        street = callData.street
    }, function(success, resultData)
        if success then
            print("Panic was triggered")
        else
            print("Unable to trigger panic")
        end
    end)
end)

RegisterNetEvent('ImperialCAD:ClearPanic')
AddEventHandler('ImperialCAD:ClearPanic', function()

    exports["ImperialCAD"]:ClearPanic(function(success, resultData)
        if success then
            print("Panic was cleared")
        else 
            print("Unable to clear community panic")
        end
    end)
end)

RegisterNetEvent("ImperialCAD:Server:NewNotify")
AddEventHandler("ImperialCAD:Server:NewNotify", function(callData)

    local d = callData or {}
    if not d then print("ImperialCAD Could not create a new dispatch, No callData was found. Returning early") return false end
    local street = d.street or "Unknown"
    local crossStreet = d.crossStreet or "N/A"
    local postal = d.postal or "00000"
    local city = d.city or "N/A"
    local county = d.county or "N/A"
    local nature = d.nature or "No Nature Provided"
    local status = d.status or "ACTIVE"
    local priority = d.priority or 2
    if not d.cords or d.cords == "" then
        print("ImperialCAD Could not create a new dispatch, No cords were found. Returning early")
        return false
    end
    local cords = d.cords
    local message = d.message or "No information provided"
    local cmessage = d.cmessage or "No Information provided"
    local job = d.job or "Unknown"

    exports["ImperialCAD"]:CreateCall({
        users_discordID = "",
        street = street,
        crossStreet = crossStreet,
        postal = postal,
        city = city,
        county = county,
        info = message,
        nature = nature,
        status = status,
        priority = priority
    }, function(success, resultData)
        if success then
            local apires = decodeJsonResponse(resultData, "new dispatch create")
            if not apires or not apires.response or not apires.response.callId then
                print("^1[API_ERROR]^7 Invalid response or call ID not found")
                return false
            end

            local callNum = apires.response.callnum
            print("New Dispatch CAD Call created successfully: Call ID -", callNum)

            local chatMessage = {
                multiline = true,
                args = {
                    "^8(ImperialCAD - New Call For Service)",
                    "^7\nPostal: ^3" .. postal ..
                    "^7\nStreet: ^3" .. street ..
                    "^7\nCross Street: ^3" .. crossStreet ..
                    "^7\nInformation: ^3" .. cmessage ..
                    "^7\nCall Number: ^3" .. callNum
                }
            }

            local successDuty, onDutyUnits = pcall(function()
                if job == "LEO" then
                    return exports["ImperialCAD"]:GetOnDutyLEOUnits()
                elseif job == "FIRE" then
                    return exports["ImperialCAD"]:GetOnDutyFireUnits()
                else
                    return exports["ImperialCAD"]:GetOnDutyUnits()
                end
            end)

            if successDuty and onDutyUnits then
                for _, playerId in ipairs(onDutyUnits) do
                    TriggerClientEvent("chat:addMessage", playerId, chatMessage)
                    TriggerClientEvent("Imperial:911BlipForOnduty", playerId, cords)
                end
                if Config.debug then print("Blips and messages sent to on-duty units.") end
            else
                TriggerClientEvent("chat:addMessage", -1, chatMessage)
                if Config.debug then print("Duty unit fetch failed. Message sent to all.") end
            end

        else
            print("New Imperial Dispatch call failed: "..resultData)
        end
    end)

end)


RegisterNetEvent("Imperial:911ChatMessage")
AddEventHandler("Imperial:911ChatMessage", function(name, street, message, crossStreet, postal, callNum)
    if not callNum then callNum = "ERROR" end
    local chatMessage = {
        multiline = true,
        args = {"^8(ImperialCAD - New Call For Service)",
            "\nName: ^3" .. name .. "^7\nPostal: ^3" .. postal .. "^7\nStreet: ^3" .. street .. 
            "^7\nCross Street: ^3" .. crossStreet .. "^7\nInformation: ^3" .. message .. "^7\nCall Number: ^3" .. callNum
        }
    }

    local success, onDutyUnits = pcall(function()
        return exports["ImperialCAD"]:GetOnDutyUnits()
    end)

    if success and onDutyUnits then
        for _, playerId in ipairs(onDutyUnits) do
            TriggerClientEvent("chat:addMessage", playerId, chatMessage)
        end
    else
        TriggerClientEvent("chat:addMessage", -1, chatMessage)
        end
end)

RegisterNetEvent("ImperialCAD:911Blip")
AddEventHandler("ImperialCAD:911Blip", function(coords)

    local success, OnDutyUnitsFound = pcall(function()
        return exports["ImperialCAD"]:GetOnDutyUnits()
     end)
     
     if success then
    for _, playerId in ipairs(OnDutyUnitsFound) do

           if Config.debug then
           print("We found ImperialDuty, Proceeding with blips")
           end

        TriggerClientEvent("Imperial:911BlipForOnduty", playerId, coords)
    end
    else

           if Config.debug then
           print("Couldnt find ImperialDuty, proceeding without blip.")
           end

    end

end)
