--[[
    Imperial Export for FiveM
DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOUR DOING!
]]--

local function getDiscordId(src)
    if src == nil then return false end
    local identifiers = GetPlayerIdentifiers(src)
    for _, v in pairs(identifiers) do
        if string.sub(v, 1, 8) == "discord:" then
            return string.gsub(v, "discord:", "")
        end
    end
    return false
end

if Config.isQB then
    
    local QBCore = exports['qb-core']:GetCoreObject({'Functions'})

    -- Hook into the character creation event
    RegisterNetEvent('qb-multicharacter:server:createCharacter')
    AddEventHandler('qb-multicharacter:server:createCharacter', function(cData)
        local src = source
        local discordId = getDiscordId(src)
    
       if Config.debug then
        print("Received Character Data (Pre-Delay): " .. json.encode(cData))
       end

        -- Wait a few seconds for the data to be properly created
        Wait(3000)  -- 3 seconds
    
        -- Fetch the updated player data from QBCore
        local Player = QBCore.Functions.GetPlayer(src)
    
        if Player then
            local citizenid = Player.PlayerData.citizenid
            local charinfo = Player.PlayerData.charinfo
            local firstname = cData.firstname
            local lastname = cData.lastname
            local birthdate = cData.birthdate
            local gender = cData.gender
            local nationality = cData.nationality
            local phone = cData.phone
            local account = cData.account
    
            if gender == 0 then
                gender = "male"
            elseif gender == 1 then
                gender = "female"
            end

            if Config.debug then
            print("✅ Character Created After Delay:")
            print("Citizen ID: " .. citizenid)
            print("Discord ID: " .. discordId)
            print("First Name: " .. firstname)
            print("Last Name: " .. lastname)
            print("Birthdate: " .. birthdate)
            print("Gender: " .. gender)
            end
        
            -- Call the NewCharacter function to send data to the API
            exports["ImperialCAD"]:NewCharacter({
                users_discordID = discordId,
                Fname = firstname,
                Mname = "",
                Lname = lastname,
                Birthdate = birthdate,
                race = "nil",
                hairC = "nil",
                eyeC = "nil",
                height = "6'",
                weight = "150",
                postal = nil,
                address = "nil",
                gender = gender,
                city = "nil",
                county = "nil",
                phonenum = phone,
                dlstatus = "none",
                citizenid = citizenid
            }, function(success, resultData)
                if success then 
                    print("✅ Character Created in CAD")
                else 
                    print("⚠️ ERROR: Could not create character in CAD.")
                end
            end)
        else
            print("⚠️ ERROR: Could not retrieve player data after delay!")
        end
    end)

    -- Hook into the character deletion event
    RegisterNetEvent('qb-multicharacter:server:deleteCharacter')
    AddEventHandler('qb-multicharacter:server:deleteCharacter', function(citizenid)
        local src = source
        local discordId = getDiscordId(src)

        if Config.debug then
            print("Received Character Deletion Request: " .. citizenid)
        end
    
        exports["ImperialCAD"]:DeleteCharacter({
            users_discordID = discordId,
            citizenid = citizenid
        }, function(success, resultData)
            if success then 
                print("✅ Character was deleted in CAD")
            else 
                    print("⚠️ ERROR: Could not delete character in CAD.")
            end
        end)
    end)

end