--[[
    Imperial Export for FiveM
DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOUR DOING!
]]--

local function checkConvar(name, description)
    local value = GetConvar(name, "")
    if not value or value == "" then
        error(string.format("Could not find required Convar '%s' for %s.", name, description))
    end
    print(string.format("%s '%s' found.", description, name))
end

checkConvar("imperial_community_id", "ImperialCAD Community ID")
checkConvar("imperialAPI", "Imperial API key")

local function debugLog(message)
    if Config.debug then
        print("[ImperialCAD] " .. message)
    end
end

local function sendCallback(callback, success, payload, context)
    if not callback then return end

    local ok, err = pcall(callback, success, payload)
    if not ok then
        print(("[ImperialCAD] %s callback failed: %s"):format(context or "API", tostring(err)))
    end
end

local function performAPIRequest(url, data, headers, callback)
    PerformHttpRequest(url, function(errorCode, resultData, resultHeaders, errorData)
    if errorCode ~= 200 then
        
        if errorCode == 500 then
            sendCallback(callback, false, "[ImperialCAD] CAD returned a temporary internal error.", "API request")
            return
        end

        debugLog(("Request failed with HTTP code %s."):format(tostring(errorCode)))
        if Config.debug and errorData and errorData ~= "" then
            print("[ImperialCAD] Error response: " .. errorData)
        elseif Config.debug and resultData and resultData ~= "" then
            print("[ImperialCAD] Response body: " .. resultData)
        end

        if callback then
            if errorData and errorData ~= "" then
                local jsonPart = errorData:match("{.*}")
                if jsonPart then
                    sendCallback(callback, false, jsonPart, "API request")
                else
                    sendCallback(callback, false, errorData, "API request")
                end
            else
                sendCallback(callback, false, "[ImperialCAD] Request failed without response data.", "API request")
            end
        end

        return
    end

    local status
    if resultData and resultData ~= "" then
        local ok, body = pcall(json.decode, resultData)
        if ok and type(body) == "table" then
            status = body.status -- "error", "RATE_LIMIT", "success", "BUSY", "LIMIT_REACHED", "USER_LIMIT", "RESERVED", etc.
        end
    end

    if status and status ~= "success" then
        debugLog(("CAD returned status '%s'."):format(tostring(status)))
        if Config.debug and resultData then
            print("[ImperialCAD] Response body: " .. resultData)
        end
        if callback then
            sendCallback(callback, false, resultData or ("Status: " .. tostring(status)), "API request")
        end
        return
    end

    if callback then
        if resultData and resultData ~= "" then
            sendCallback(callback, true, resultData, "API request")
        else
            sendCallback(callback, true, "[ImperialCAD] Request succeeded without response data.", "API request")
        end
    end

    debugLog("Request completed successfully.")

    end, 'POST', json.encode(data), headers)
end

function Create911Call(data, callback)
    local data = {
        commId = GetConvar("imperial_community_id", ""),
        name = data.name,
        street = data.street,
        cross_street = data.crossStreet,
        info = data.info,
        postal = data.postal,
        city = data.city,
        county = data.county
    }
    local headers = {
        ["Content-Type"] = "application/json",
        ["APIKEY"] = GetConvar("imperialAPI", "")
    }
    performAPIRequest("https://imperialcad.app/api/1.1/wf/911", data, headers, callback)
    
    if Config.debug then
       print("[Imperial_Export_Create911Call] Attempting to create a 911 call.")
    end

end

function DeleteCall(data, callback)
    local data = {
        callId = data.callId,
        discordId = data.discordId or data.discordid,
        communityId = GetConvar("imperial_community_id", "")
    }
    local headers = {
        ["Content-Type"] = "application/json",
        ["APIKEY"] = GetConvar("imperialAPI", "")
    }
    performAPIRequest("https://imperialcad.app/api/1.1/wf/CallDelete", data, headers, callback)

    if Config.debug then
    print("[Imperial_Export_DeleteCall] Attempting to delete a call.")
    end

end

function CreateCall(data, callback)
    local data = {
        commId = GetConvar("imperial_community_id", ""),
        users_discordID = data.users_discordID,
        street = data.street,
        cross_street = data.crossStreet or data.cross_street,
        postal = data.postal,
        city = data.city,
        county = data.county,
        info = data.info,
        nature = data.nature,
        status = data.status,
        priority = data.priority
    }
    local headers = {
        ["Content-Type"] = "application/json",
        ["APIKEY"] = GetConvar("imperialAPI", "")
    }
    performAPIRequest("https://imperialcad.app/api/1.1/wf/CallCreate", data, headers, callback)

    if Config.debug then
      print("[Imperial_Export_CreateCall] Attempting to create a new call.")
    end

end

function AttachCall(data, callback)
    local data = {
        commId = GetConvar("imperial_community_id", ""),
        users_discordID = data.users_discordID,
        callnum = data.callnum
    }
    local headers = {
        ["Content-Type"] = "application/json",
        ["APIKEY"] = GetConvar("imperialAPI", "")
    }
    performAPIRequest("https://imperialcad.app/api/1.1/wf/AttachCall", data, headers, callback)

     if Config.debug then
    print("[Imperial_Export_AttachCall] Attempting to attach player " .. source .. " to call " .. data.callnum)
     end

end

function NewCallNote(data, callback)
    local data = {
        commId = GetConvar("imperial_community_id", ""),
        users_discordID = data.users_discordID,
        description = data.description
    }
    local headers = {
        ["Content-Type"] = "application/json",
        ["APIKEY"] = GetConvar("imperialAPI", "")
    }
    performAPIRequest("https://imperialcad.app/api/1.1/wf/callnote", data, headers, callback)

    if Config.debug then
      print("[Imperial_Export_NewCallNote] Attempting to create a new call note.")
    end

end

function Booter(data, callback)
    local data = {
        commId = GetConvar("imperial_community_id", ""),
        users_discordID = data.users_discordID,
    }
    local headers = {
        ["Content-Type"] = "application/json",
        ["APIKEY"] = GetConvar("imperialAPI", "")
    }
    if Config.debug then
    print("Discord ID:" .. data.users_discordID .. "Community ID:" .. data.commId)
    end

    performAPIRequest("https://imperialcad.app/api/1.1/wf/offduty", data, headers, callback)

    if Config.debug then
      print("[Imperial_Export_Booter] Attempting to mark a user off duty in CAD.")
    end

end

function Panic(data, callback)
    local data = {
        commId = GetConvar("imperial_community_id", ""),
        users_discordID = data.users_discordID,
        postal = data.postal,
        street = data.street
    }
    local headers = {
        ["Content-Type"] = "application/json",
        ["APIKEY"] = GetConvar("imperialAPI", "")
    }
    performAPIRequest("https://imperialcad.app/api/1.1/wf/panic", data, headers, callback)

    if Config.debug then
     print("[Imperial_Export_Panic] Attempting to trigger a user panic in CAD.")
    end

end

function ClearPanic(callback)
    local data = {
        commId = GetConvar("imperial_community_id", "")
    }
    local headers = {
        ["Content-Type"] = "application/json",
        ["APIKEY"] = GetConvar("imperialAPI", "")
    }
    performAPIRequest("https://imperialcad.app/api/1.1/wf/clearpanic", data, headers, callback)

    if Config.debug then
     print("[Imperial_Export_ClearPanic] Attempting to clear a community panic.")
    end

end

function CheckPlate(data, callback)
    local plate = data and data.plate

    if not plate or plate == "" then
        sendCallback(callback, false, "[ImperialCAD] Plate lookup skipped: missing plate.", "CheckPlate")
        return
    end

    local requestData = {
        communityId = GetConvar("imperial_community_id", ""),
        plate = plate
    }
    local headers = {
        ["Content-Type"] = "application/json",
        ["APIKEY"] = GetConvar("imperialAPI", "")
    }
    performAPIRequest("https://imperialcad.app/api/1.1/wf/checkplate", requestData, headers, callback)

    if Config.debug then
        print("[ImperialCAD] Checking plate " .. plate .. ".")
    end

end

function GetUnit(data, callback)
    local discordId = data and data.users_discordID
    if not discordId or discordId == "" then
        sendCallback(callback, false, "[ImperialCAD] Unit lookup skipped: missing Discord ID.", "GetUnit")
        return
    end

    local data = {
        communityId = GetConvar("imperial_community_id", ""),
        users_discordID = discordId
    }
    local headers = {
        ["Content-Type"] = "application/json",
        ["APIKEY"] = GetConvar("imperialAPI", "")
    }
    performAPIRequest("https://imperialcad.app/api/1.1/wf/GetUnit", data, headers, callback)

    if Config.debug then
    print("[ImperialCAD] Attempting to get unit " .. discordId .. ".")
    end

end

exports('Create911Call', Create911Call)
exports('DeleteCall', DeleteCall)
exports('CreateCall', CreateCall)
exports('AttachCall', AttachCall)
exports('NewCallNote', NewCallNote)
exports('Booter', Booter)
exports('CheckPlate', CheckPlate)
exports('Panic', Panic)
exports('ClearPanic', ClearPanic)
exports('GetUnit', GetUnit)
